- name: Ensure /etc/apt/keyrings exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Kubernetes APT signing key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'

- name: Check if key is ASCII-armored
  ansible.builtin.shell: grep -q "BEGIN PGP PUBLIC KEY BLOCK" /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  register: key_format_check
  failed_when: false
  changed_when: false

- name: Convert to binary if ASCII-armored
  ansible.builtin.shell: |
    gpg --dearmor < /etc/apt/keyrings/kubernetes-apt-keyring.gpg > /etc/apt/keyrings/kubernetes-apt-keyring.gpg.tmp
    mv /etc/apt/keyrings/kubernetes-apt-keyring.gpg.tmp /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  when: key_format_check.rc == 0
  become: true

- name: Add the Kubernetes APT repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg]
      https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /
    filename: kubernetes
    state: present
    update_cache: true
  register: repo_added

- name: Install kubelet, kubeadm
  ansible.builtin.apt:
    name:
      - "kubelet={{ kube_version }}"
      - "kubeadm={{ kube_version }}"
    state: present
    update_cache: false
  become: true

- name: Hold Kubernetes packages (if not already held)
  community.general.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
  become: true