---
- name: Restart wazuh-indexer
  ansible.builtin.systemd:
    name: wazuh-indexer
    state: restarted

- name: Restart wazuh-manager
  ansible.builtin.systemd:
    name: wazuh-manager
    state: restarted

- name: Restart wazuh-dashboard
  ansible.builtin.systemd:
    name: wazuh-dashboard
    state: restarted

- name: Restart filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted

- name: Restart vector
  ansible.builtin.systemd:
    name: vector
    state: restarted
  failed_when: false
