- name: Fetch join.sh from first control-plane node
  ansible.builtin.fetch:
    src: /tmp/join.sh
    dest: /tmp/join.sh
    flat: yes
  run_once: true

- name: Run kubeadm join using fetched script
  ansible.builtin.shell: bash /tmp/join.sh
  args:
    creates: /etc/kubernetes/kubelet.conf
