- name: Install Docker from Ubuntu repo
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Ensure Docker service is started & enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
