---
- name: Restart crowdsec container
  community.docker.docker_compose:
    project_src: "{{ crowdsec_config_dir }}"
    state: present
    restarted: true

- name: Restart crowdsec bouncer
  ansible.builtin.systemd:
    name: crowdsec-firewall-bouncer
    state: restarted
