---
jellyfin_version: "10.10.6"
jellyfin_config_dir: /opt/jellyfin/config
jellyfin_cache_dir: /opt/jellyfin/cache
jellyfin_nfs_server: "192.168.1.15"
jellyfin_media_nfs_path: "/mnt/tank/media"
jellyfin_media_mount: "/mnt/media"
jellyfin_http_port: 8096
nvidia_driver_version: "570"
