- name: Download Calico manifest
  get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v3.30.2/manifests/calico.yaml
    dest: /tmp/calico.yaml
  run_once: true

- name: Apply Calico manifests declaratively
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    src: /tmp/calico.yaml
  run_once: true
