---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart ansible-proxmox timer
  ansible.builtin.systemd:
    name: ansible-proxmox.timer
    state: restarted

- name: Restart ansible-security timer
  ansible.builtin.systemd:
    name: ansible-security.timer
    state: restarted
