- name: Install MariaDB
  apt:
    name: [mariadb-server, galera-4, rsync]
    state: present

- name: Configure Galera
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf

- name: Start and enable MySQL
  systemd:
    name: mysql
    enabled: true
    state: started