- name: Dump default containerd config (once only)
  ansible.builtin.command: containerd config default | sudo tee /etc/containerd/config.toml > /dev/null
  args:
    creates: /etc/containerd/config.toml

- name: Enable SystemdCgroup in containerd (only if file is present)
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'
    backup: yes

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
