---
- name: Deploy monitoring agents to all Linux VMs
  hosts: linux
  become: true
  vars_files:
    - ../group_vars/vault.yml
  roles:
    - monitoring/node_exporter
    - role: monitoring/vector
      when: "'nas' not in group_names"
    - role: unattended_upgrades
      when: "'nas' not in group_names"
